name: DAST with OWASP ZAP

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  zap-scan:
    runs-on: ubuntu-latest

    services:
      zap:
        image: owasp/zap2docker-stable:latest
        options: --health-cmd "curl -f http://localhost:8080" --health-timeout 30s --health-start-period 30s --health-retries 3
        ports:
          - 8080:8080

    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Set up TARGET_URL
        run: echo "TARGET_URL=${{ secrets.TARGET_URL }}" >> $GITHUB_ENV

      - name: Set up zap-rules.txt
        run: echo "${{ secrets.ZAP_RULES }}" > ./zap-rules.txt  # Se for um segredo no GitHub

      - name: Run ZAP Scan
        run: |
          docker run -t owasp/zap2docker-stable zap-baseline.py -t $TARGET_URL -r reports/zap_report.html -c zap-config.yaml -x ./zap-rules.txt

      - name: Upload ZAP report
        uses: actions/upload-artifact@v3
        with:
          name: zap-report
          path: reports/zap_report.html
